### ISSUE TITLE
test rotation scan notes + todo

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#589]
- [ ] - direction is messy - gate width must be positive
- [ ] - eiger setup needs one trigger with total #imgs - reverse logic in eiger `set_num_triggers_and_captures`
- [ ] - filewriter errors not being reset
- [ ] - set gate start adjustment for shutter opening time
- [ ] - enable softin1 for opening shutter
- [ ] - there was a random filewriter error, didn't repeat itself
- [ ] - increment run number/update sample

**Comment by DominicOram** [comment]
Closed for #607
